const titleOverrides: Record<string, string> = {
  "/bedankt-voor-uw-aanvraag/": "Thank you for your request | Mondzorgpraktijk Veenendaal",
  "/tandarts-veenendaal-maak-direct-een-afspraak/": "Dentist in Veenendaal – Make an appointment",
  "/ons-team/huusder-barmer-2/": "Huusder Barmer | Mondzorgpraktijk Veenendaal",
  "/ons-team/wenda-van-de-lagemaat/": "Wenda van de Lagemaat | Mondzorgpraktijk Veenendaal",
  "/behandelingen/": "Treatments | Mondzorgpraktijk Veenendaal",
  "/diversity-policy/": "Diversity Policy | Mondzorgpraktijk Veenendaal",
  "/ethics-policy/": "Ethics Policy | Mondzorgpraktijk Veenendaal",
  "/actionable-feedback-policy/": "Actionable Feedback Policy | Mondzorgpraktijk Veenendaal",
  "/behandelingen/angst-tandartsangst/": "Dental anxiety care | Mondzorgpraktijk Veenendaal",
  "/behandelingen/white-spots-verwijderen-witte-vlekken/": "White spot treatment | Mondzorgpraktijk Veenendaal",
  "/behandelingen/pijnloze-gebitsreiniging-gbt/": "Comfortable dental cleaning (GBT)",
  "/behandelingen/tandvleesbehandeling-parodontitis/": "Gum treatment for periodontitis",
  "/behandelingen/preventie-mondhygienist/": "Prevention & dental hygiene",
  "/behandelingen/tandenbleken/": "Professional teeth whitening in Veenendaal",
  "/behandelingen/facings-voor-een-stralende-glimlach/": "Veneers for a radiant smile",
  "/behandelingen/aligner-doorzichtige-beugel/": "Clear aligners",
  "/behandelingen/tanden-trekken-extracties/": "Tooth extraction",
  "/behandelingen/prothese-kunstgebit/": "Dentures | Mondzorgpraktijk Veenendaal",
  "/behandelingen/kronen-en-bruggen/": "Crowns and bridges | Mondzorgpraktijk Veenendaal",
  "/behandelingen/wortelkanaalbehandeling/": "Root canal treatment | Mondzorgpraktijk Veenendaal",
  "/behandelingen/vullingen-gaatjes-vullen/": "Dental fillings | Mondzorgpraktijk Veenendaal",
  "/behandelingen/periodieke-controles/": "Periodic dental check-ups | Mondzorgpraktijk Veenendaal",
  "/blog/": "Journal | Mondzorgpraktijk Veenendaal",
  "/ons-team/cristian-zandi/": "Cristian Zandi | Mondzorgpraktijk Veenendaal",
  "/mondzorg/": "Oral care | Mondzorgpraktijk Veenendaal",
  "/kindertandheelkunde/": "Paediatric dentistry in Veenendaal",
  "/algemene-tandheelkunde/": "General dentistry in Veenendaal",
  "/maak-een-afspraak-2/": "Make an appointment | Mondzorgpraktijk Veenendaal",
  "/maak-een-afspraak-1/": "Make an appointment | Mondzorgpraktijk Veenendaal",
  "/informatie/": "Patient information | Mondzorgpraktijk Veenendaal",
  "/contact/": "Contact | Mondzorgpraktijk Veenendaal",
  "/de-praktijk/": "Our practice | Mondzorgpraktijk Veenendaal",
  "/ons-team/": "Our team | Mondzorgpraktijk Veenendaal",
  "/afspraak-maken/": "Make an appointment | Mondzorgpraktijk Veenendaal",
  "/": "Dentist in Veenendaal | Mondzorgpraktijk Veenendaal",
  "/kind-wil-niet-tandenpoetsen/": "Child refuses to brush their teeth? Practical tips for parents",
  "/invisalign-tijdens-zwangerschap/": "Invisalign during pregnancy: safety, risks and advice",
  "/waarom-onzichtbare-beugel-beter-is-dan-slotjesbeugel/": "Clear aligners or fixed braces: what are the differences?",
  "/parodontitis-behandeling-of-kunstgebit/": "Periodontitis treatment or dentures: how to choose",
  "/gewoon-gaaf-methode-kindertandheelkunde/": "What is the Gewoon Gaaf method? Preventive care for children",
  "/kunstgebit-onderhouden-praktische-tips/": "How to care for dentures: practical, evidence-based advice",
  "/kindertandangst-tips/": "Effective ways to help children with dental anxiety",
  "/symptomen-problemen-verstandskies/": "How do you know if a wisdom tooth is causing problems?",
  "/waarom-tanden-pijn-bij-koude-of-warme-dranken/": "Tooth pain with hot or cold drinks: causes and advice",
  "/porseleinen-of-composiet/": "Porcelain or composite veneers: how to choose",
  "/preventieve-mondzorg-gezondheid/": "Preventive oral care: guidance for healthy teeth",
  "/waarom-gebitsreiniging/": "Why is professional dental cleaning important?",
  "/leeftijd-eerste-tandartsbezoek/": "When should children first visit the dentist?",
  "/ontstoken-tandvlees-symptomen-behandeling/": "Inflamed gums: symptoms and treatment",
  "/kiezen-trekken-voor-een-beugel/": "Extracting teeth for braces: when is it necessary?",
  "/bang-voor-de-tandarts/": "Afraid of the dentist? Advice from experienced dentists",
  "/hoe-werken-doorzichtige-aligners/": "How do clear aligners work?",
  "/wanneer-vullingen-vervangen/": "When should fillings be replaced? Signs and advice",
  "/alles-wat-je-moet-weten-over-het-vullen-van-tanden/": "How does a dentist fill a cavity? Step-by-step explanation",
  "/hoe-vaak-tanden-bleken/": "How often can you whiten your teeth safely?",
  "/vanaf-welke-leeftijd-tanden-bleken/": "Teeth whitening: minimum age and important advice",
  "/risico-tanden-bleken/": "Teeth whitening: risks and how to reduce them",
};

const replacements: Array<[RegExp, string]> = [
  [/Oral [Cc]are [Pp]ractice Veenendaal/g, "Mondzorgpraktijk Veenendaal"],
  [/Oral [Cc]are Veenendaal/g, "Mondzorgpraktijk Veenendaal"],
  [/Mouth [Cc]are [Pp]ractice Veenendaal/g, "Mondzorgpraktijk Veenendaal"],
  [/Mouth [Cc]are Veenendaal/g, "Mondzorgpraktijk Veenendaal"],
  [/oral hygienicist/gi, "dental hygienist"],
  [/mouth hygienists/gi, "dental hygienists"],
  [/mouth hygienist/gi, "dental hygienist"],
  [/mouth hygiene/gi, "oral hygiene"],
  [/dental cleansing/gi, "professional dental cleaning"],
  [/paediatric surgery/gi, "paediatric dentistry"],
  [/pediatrician/gi, "paediatric dentist"],
  [/transparent algorithms/gi, "clear aligners"],
  [/transparent algorithm/gi, "clear aligner"],
  [/algorithms/gi, "aligners"],
  [/algorithm/gi, "aligner"],
  [/transparent brackets/gi, "clear aligners"],
  [/transparent bracket/gi, "clear aligner"],
  [/invisible bracket/gi, "clear aligner"],
  [/parodontitis/gi, "periodontitis"],
  [/Common Cool Method/gi, "Gewoon Gaaf method"],
  [/Simply Cool method/gi, "Gewoon Gaaf method"],
  [/punctures/gi, "cavities"],
  [/\bholes\b/gi, "cavities"],
  [/\bhole\b/gi, "cavity"],
  [/\bpiercing\b/gi, "cavities"],
  [/tartars/gi, "tartar"],
  [/\bProsthesis\b/g, "Dentures"],
  [/\bprostheses\b/gi, "dentures"],
  [/\bFills\b/g, "Fillings"],
  [/Periodical monitoring/gi, "Periodic check-ups"],
  [/Periodical control/gi, "Periodic check-ups"],
  [/Periodic Control/gi, "Periodic check-ups"],
  [/Crown and bridge/gi, "Crowns and bridges"],
  [/allround/gi, "all-round"],
  [/Bar work/gi, "Reception duties"],
  [/Bailiff work/gi, "Reception duties"],
  [/Gingival treatment/gi, "Gum treatment"],
  [/tooth meat disorders/gi, "gum disease"],
  [/tooth meat/gi, "gums"],
  [/raspberry hair/gi, "frayed bristles"],
  [/\bragers\b/gi, "interdental brushes"],
  [/floss wire/gi, "dental floss"],
  [/mouthwashing/gi, "mouthwash"],
  [/\bCabins:/g, "Cavities:"],
  [/dental bone/gi, "dentine"],
  [/\bglaze\b/gi, "tooth enamel"],
  [/teeth nerve/gi, "tooth nerve"],
  [/permanent selection/gi, "permanent teeth"],
  [/missing teeth or choose/gi, "missing teeth or molars"],
  [/healthy choices for braces/gi, "healthy teeth for braces"],
  [/Choose which:/gi, "Which teeth:"],
  [/Why draw tooth:/gi, "Why extract teeth:"],
  [/Choosing to pull braces/gi, "Extracting teeth for braces"],
  [/A teeth that are/gi, "Teeth that are"],
  [/fixed bracket/gi, "fixed braces"],
  [/traditional brackets/gi, "traditional braces"],
  [/metal brackets/gi, "metal braces"],
  [/\bFacings\b/g, "Veneers"],
  [/\bfacings\b/g, "veneers"],
  [/\bcomposed\b/gi, "composite"],
  [/silver\/tin\/copper\/sink/gi, "silver/tin/copper/zinc"],
  [/for choice,/gi, "for molars,"],
  [/Teeth bleaching/gi, "Teeth whitening"],
  [/tooth bleaching/gi, "tooth whitening"],
  [/tooth palening/gi, "tooth whitening"],
  [/tooth pale/gi, "tooth whitening"],
  [/Home palette/gi, "At-home whitening"],
  [/Home pales/gi, "At-home whitening"],
  [/home pale/gi, "at-home whitening"],
  [/pale gels/gi, "whitening gels"],
  [/bleachers with bleach/gi, "custom trays with whitening gel"],
  [/in-practice bleaching/gi, "in-practice whitening"],
  [/self bleaching/gi, "at-home whitening"],
  [/\bbleaching\b/gi, "whitening"],
  [/MONDESONITY/gi, "ORAL HEALTH"],
  [/COMPLETIONS/gi, "FILLINGS"],
  [/WHITE VICTIMS ON TANDS/gi, "WHITE SPOTS ON TEETH"],
  [/SYMPTOMS OF MILK DISCLOSURE/gi, "SYMPTOMS OF GUM INFLAMMATION"],
  [/WHAT DOES A MONDHYGIENIST DO\?/gi, "WHAT DOES A DENTAL HYGIENIST DO?"],
  [/PITCH AND CLEANING OPINION/gi, "BRUSHING AND CLEANING ADVICE"],
  [/DIFFERENCE BETWEEN HOUSEBYES AND IN- PRACTICAL BREAKS/gi, "AT-HOME VS IN-PRACTICE WHITENING"],
  [/How many teeth whitening\?/gi, "How often can you whiten your teeth?"],
  [/Your Teeth Bleached/gi, "Teeth whitening"],
  [/Pediatrics Veenendaal/gi, "Paediatric dentistry in Veenendaal"],
  [/HOW ARE WE GOING TO FEAR\?/gi, "HOW WE HELP WITH DENTAL ANXIETY"],
  [/not weird/gi, "not unusual"],
  [/delay behaviour/gi, "delaying treatment"],
  [/Soft communication/gi, "Clear, gentle communication"],
  [/Atmospheric environment/gi, "Calming environment"],
  [/Do you lose white spots\?/gi, "Would you like to reduce white spots?"],
  [/structural structure/gi, "structure"],
  [/fills the demineralization/gi, "infiltrates the demineralised enamel"],
  [/corrects the demineralisation process/gi, "seals the porous enamel"],
  [/remove it aimlessly/gi, "remove it precisely"],
  [/undesirable substances/gi, "deposits"],
  [/gum fears/gi, "gum sensitivity"],
  [/we represent the importance/gi, "we emphasise the importance"],
  [/comfortable laughing, talking and eating/gi, "comfortable smiling, talking and eating"],
  [/dental plaque\/stroke/gi, "dental plaque and staining"],
  [/repealed gums/gi, "receding gums"],
  [/often without brackets/gi, "often without discomfort"],
  [/What are faces\?/gi, "What are veneers?"],
  [/Composite faces/gi, "Composite veneers"],
  [/Porcelain faces/gi, "Porcelain veneers"],
  [/thin shields/gi, "thin shells"],
  [/MATERIAL: US COMPOSITE\. PORSELEIN/gi, "MATERIALS: COMPOSITE OR PORCELAIN"],
  [/Two agreements/gi, "Two appointments"],
  [/\bagreements\b/gi, "appointments"],
  [/sharpening, printing/gi, "shaping and taking impressions"],
  [/SPECIES OF EXTRACTION: SIMPLE & CHIRUGIC/gi, "TYPES OF EXTRACTION: SIMPLE & SURGICAL"],
  [/crooked tooth or overpopulation of the tooth/gi, "a poorly positioned tooth or dental crowding"],
  [/Call, local anaesthetic/gi, "Consultation, local anaesthetic"],
  [/SWILLING AND NAZORG/gi, "SWELLING AND AFTERCARE"],
  [/\bclammers\b/gi, "clasps"],
  [/\blaborative work\b/gi, "laboratory work"],
  [/How does it measure\?/gi, "How are dentures fitted?"],
  [/MATERIAL OPTIONS: KERAMIC, PORSELEIN, ZIRKONIUM/gi, "MATERIAL OPTIONS: CERAMIC, PORCELAIN, ZIRCONIA"],
  [/suitable for choice/gi, "suitable for molars"],
  [/hard\/sticky diet/gi, "hard or sticky foods"],
  [/When do you need a refill\?/gi, "When do you need a filling?"],
  [/TYPE OF TANDVOLUTION/gi, "TYPES OF FILLING"],
  [/Remove Dental/gi, "Dental cleaning"],
  [/Treatment of children/gi, "Paediatric dentistry"],
  [/Transparent Bowl/gi, "Clear aligners"],
  [/Teeth Bleken/gi, "Teeth whitening"],
  [/Scientific Underbuilt Methods/gi, "Evidence-based methods"],
  [/adhesive removal/gi, "plaque removal"],
  [/Journal of Clinical Periodicology/gi, "Journal of Clinical Periodontology"],
  [/Advantages: habitation\/prevention/gi, "Benefits: familiarisation and prevention"],
  [/Inspection of teeth and teeth, gum control/gi, "Examination of teeth and molars, gum assessment"],
  [/How many times do I have to come over\?/gi, "How often should I visit?"],
  [/How many times do I have to go to the dental hygienist\?/gi, "How often should I visit the dental hygienist?"],
  [/How many times do I have to go to the dentist for a checkup\?/gi, "How often should I visit the dentist for a check-up?"],
  [/risk groups/gi, "high-risk patients"],
  [/Regular checks to check/gi, "Regular check-ups to monitor"],
  [/Restoring a cavity in a tooth by filling with/gi, "Restoring a cavity with"],
  [/\bNazorg\b/gi, "aftercare"],
  [/\bPorselein\b/gi, "porcelain"],
  [/\bKeramic\b/gi, "ceramic"],
  [/transparent plastic cases/gi, "clear plastic trays"],
  [/parodontal/gi, "periodontal"],
  [/traditional braces consistently wear/gi, "traditional braces when worn consistently"],
  [/permanent selection/gi, "permanent teeth"],
  [/Sickness insurance/gi, "Health insurance"],
  [/frosting damage/gi, "enamel damage"],
  [/we hire new patients/gi, "we are accepting new patients"],
  [/MAKE A DEAL/gi, "MAKE AN APPOINTMENT"],
  [/SUBSCRIBE/gi, "REGISTER"],
  [/\s+([.,])/g, "$1"],
  [/(?:\s*\.\s*){2,}/g, " — "],
];

export function polishEnglish(value: string) {
  return replacements.reduce((result, [pattern, replacement]) => result.replace(pattern, replacement), value).trim();
}

export function englishTitle(path: string, fallback: string) {
  return titleOverrides[path] ?? polishEnglish(fallback);
}
